"""ゲーム定数"""

# リリース情報
VERSION = "0.1.0"

# タイトル（ウィンドウ・タイトル画面に使用）
GAME_TITLE = "芋虫ホッケー"
GAME_SUBTITLE = "這うと体節が壁になる、エアホッケー"
GAME_TAGLINE = "先取3点 ／ 這うと体節 ／ Shiftでダッシュ"
CPU_LABEL = "CPU芋虫"
P1_LABEL = "P1芋虫"
P2_LABEL = "P2芋虫"

# 画面
SCREEN_W = 800
SCREEN_H = 600
FPS = 60

# 色 — 黒背景 × 白枠 × ネオン（Wiiホッケー風）
BG_COLOR = (0, 0, 0)
TABLE_COLOR = (6, 14, 8)
TABLE_BORDER = (255, 255, 255)
TABLE_BORDER_WIDTH = 4
TABLE_GRID_COLOR = (22, 22, 28)
CENTER_LINE_COLOR = (60, 60, 70)
HUD_COLOR = (240, 240, 245)
P1_COLOR = (0, 230, 255)
P2_COLOR = (255, 70, 190)
P1_NEON = (0, 255, 255)
P2_NEON = (255, 90, 210)
PUCK_COLOR = (255, 255, 255)
PUCK_NEON_HEAT = (255, 140, 80)

# テーブル（画面の 80% 以上）
HUD_H = 52
TABLE_MARGIN_X = 16
TABLE_Y = HUD_H + 8
TABLE_W = SCREEN_W - TABLE_MARGIN_X * 2
TABLE_H = SCREEN_H - TABLE_Y - 16

# ゴール
GOAL_WIDTH_RATIO = 0.29

# 勝敗
WIN_SCORE = 3
GOAL_RESET_DELAY = 1.5

# 芋虫（ラケット）
PADDLE_SPEED = 310.0
PADDLE_DASH_SPEED = 500.0
PADDLE_WIDTH_RATIO = 0.18 * 0.25 * 1.35
PADDLE_SIZE_AXIS = "height"
_CATERPILLAR_AXIS = TABLE_H if PADDLE_SIZE_AXIS == "height" else TABLE_W
CATERPILLAR_BODY_RADIUS = _CATERPILLAR_AXIS * PADDLE_WIDTH_RATIO / 2
PADDLE_PUCK_COOLDOWN = 0.12
PADDLE_PUCK_SEPARATION = 6.0
PUCK_PADDLE_MIN_EXIT = 140.0
PADDLE_HIT_FORGIVENESS = 10.0
PADDLE_PUCK_IMPULSE = 1.15
PADDLE_CHASE_HIT_SPEED = 55.0
PADDLE_PUCK_IGNORE_TIME = 0.10
PADDLE_CLOSE_PUCK_MARGIN = 26.0
PADDLE_CLOSE_PUCK_MIN_EXIT = 385.0
PADDLE_CLOSE_PUCK_IMPULSE = 1.30
PADDLE_CLOSE_PUCK_IGNORE_TIME = 0.18
PADDLE_CLOSE_PUCK_SEPARATION = 11.0
PADDLE_CLOSE_PUCK_SPEED_RATIO = 1.18
PADDLE_DASH_PUCK_MIN_EXIT = PADDLE_DASH_SPEED * 1.22
PADDLE_DASH_PUCK_IMPULSE = 0.0
PADDLE_DASH_PUCK_IGNORE_TIME = 0.32
PADDLE_DASH_HIT_FORGIVENESS = 4.0
PADDLE_DASH_PUCK_SEPARATION = 10.0
PADDLE_DASH_PUCK_SPEED_RATIO = 1.22
PADDLE_DASH_PUCK_SEP_MARGIN = 95.0
PADDLE_DASH_SWEEP_FORGIVENESS = 8.0
PUCK_DASH_HIT_MAX_SPEED = 640.0
PADDLE_HEAD_ON_DOT = 0.52
PADDLE_HEAD_ON_MIN_EXIT_RATIO = 1.22
PADDLE_HEAD_ON_MIN_EXIT = PADDLE_SPEED * PADDLE_HEAD_ON_MIN_EXIT_RATIO
PADDLE_HEAD_ON_SEP_MARGIN = 72.0
PADDLE_HEAD_ON_REL_SEP = 95.0
PADDLE_HEAD_ON_IGNORE_TIME = 0.24
WALL_GRIND_MARGIN = 24.0
WALL_GRIND_ALLOW_TIME = 0.40
WALL_GRIND_MAX_SPEED = 265.0
WALL_GRIND_SLIP_EXIT = 330.0
WALL_GRIND_SLIP_IGNORE = 0.22
WALL_PINCH_ESCAPE_BIAS = 0.62
HIT_JITTER_CHANCE = 0.32
HIT_JITTER_HEAD_CHANCE = 0.24
HIT_JITTER_ANGLE = 0.26

# パック（葉っぱ）
PUCK_RADIUS = 15
PUCK_MAX_SPEED = 430.0
PUCK_MIN_SPEED = 80.0
ELASTICITY = 1.0

# 体節壁（軌跡）
FENCE_HALF_WIDTH = CATERPILLAR_BODY_RADIUS
FENCE_BOOST = 200.0
FENCE_MIN_LENGTH = 12.0
TRAIL_SEGMENT_INTERVAL = CATERPILLAR_BODY_RADIUS * 1.82
TRAIL_MAX_GAP = CATERPILLAR_BODY_RADIUS * 2.1
TRAIL_MIN_SPEED = 50.0
TRAIL_WALL_LIFETIME = 2.6
TRAIL_WALL_MAX_PER_PLAYER = 8
TRAIL_GOAL_ZONE_RATIO = 0.22
TRAIL_GOAL_LIFETIME = 0.45
TRAIL_SPAWN_COOLDOWN = 0.07
TRAIL_SPAWN_CLEARANCE = 5.0
TRAIL_FADE_START_RATIO = 0.45
TRAIL_WALL_MIN_BRIGHTNESS = 0.28
TRAIL_CENTER_ZONE_RATIO = 0.18
TRAIL_CENTER_BONUS = 0.5

# 体節貫通 — 高速・連続ヒット・ダッシュ後は勢いを保って抜ける
FENCE_BREACH_SPEED = 330.0
FENCE_BREACH_DIR_MIN = 70.0
FENCE_BREACH_BOOST = 55.0
FENCE_BREACH_MOMENTUM_RETAIN = 0.88
FENCE_CHAIN_WINDOW = 0.45
FENCE_CHAIN_HITS_BEFORE_BREACH = 2
FENCE_DASH_BREACH_WINDOW = 0.32

# 効果音・BGM
SOUND_ENABLED = True
BGM_ENABLED = True
BGM_TITLE_VOLUME = 0.42
BGM_BATTLE_VOLUME = 0.30

# ラリーエスカレーション（壁反射のたびに加速）
RALLY_BOUNCE_BOOST = 0.045
RALLY_BOUNCE_MAX_MULT = 1.7

# カウントダウン
COUNTDOWN_START = 3
